version: '3.8'
services:
  app:
    container_name: go_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_NAME=postgres
      - DB_PORT=5432
    networks:
      - app-network

  db:
    container_name: postgres_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"  # Expose PostgreSQL default port 5432 to the host
    networks:
      - app-network

  migrate:
    image: migrate/migrate
    volumes:
      - ./schema:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:${DB_PASSWORD}@db:5436/postgres?sslmode=disable", "up"]
    depends_on: 
       - db

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

