version: '3.8'
services:
  app:
    container_name: go_app
    build: .
    command: ./wait-for-postgres.sh db ./main
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - app-network

  db:
    container_name: postgres_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"  # Expose PostgreSQL default port 5432 to the host
    networks:
      - app-network

  migrate:
    image: migrate/migrate
    networks:
        - app-network
    volumes:
      - ./schema:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:test@db:5432/postgres?sslmode=disable", "up"]
    depends_on: 
       - db
       - app

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

